#!/bin/sh
ssh ubuntu@3.36.90.60 <<EOF
    cd ~/kangaroo-backend	
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh 
    nvm install 16.3.0	
    npm install
    npm install -g pm2
    npm cache clean --force
    rm package-lock.json
    rm -rf ./node-modules/
    npm --verbose install
    pm2 restart ecosystem.config.js
    exit
EOF
